// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuFZdh2D-iYUKpHUhv5houBIW_kiCEf1k',
    appId: '1:556393416525:web:d1330094032085cee29904',
    messagingSenderId: '556393416525',
    projectId: 'gemini-landscaping-flutter',
    authDomain: 'gemini-landscaping-flutter.firebaseapp.com',
    storageBucket: 'gemini-landscaping-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwHxHLvrknwnSkhS3w8hCQEntUejX2nkY',
    appId: '1:556393416525:android:685bb456eca8659ee29904',
    messagingSenderId: '556393416525',
    projectId: 'gemini-landscaping-flutter',
    storageBucket: 'gemini-landscaping-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDHd_Z20593DvovunZcGvNSEVbKUiz_FU',
    appId: '1:556393416525:ios:a7482f7781033cd3e29904',
    messagingSenderId: '556393416525',
    projectId: 'gemini-landscaping-flutter',
    storageBucket: 'gemini-landscaping-flutter.appspot.com',
    iosClientId: '556393416525-kbbnlkclvr9s3i9sh0h6ipejofth21m6.apps.googleusercontent.com',
    iosBundleId: 'com.example.geminiLandscapingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDHd_Z20593DvovunZcGvNSEVbKUiz_FU',
    appId: '1:556393416525:ios:a7482f7781033cd3e29904',
    messagingSenderId: '556393416525',
    projectId: 'gemini-landscaping-flutter',
    storageBucket: 'gemini-landscaping-flutter.appspot.com',
    iosClientId: '556393416525-kbbnlkclvr9s3i9sh0h6ipejofth21m6.apps.googleusercontent.com',
    iosBundleId: 'com.example.geminiLandscapingApp',
  );
}
